### PR TITLE
Signature aggregation API fixes for small items

### LINKED ISSUE #381: Small Warp Signature API Standardization Items
**Context and scope**
#361 introduces the scaffolding for fetching an arbitrary aggregate signature via API request. There a handful of small clean up items that will bring its initial implementation more inline with our other API standards:
- [ ] Raw message should be hexadecimal encoded in request (with optional 0x prefix). We generally have not used base64 encoding anywhere.
- [ ] Response body fields should also be hexadecimal encoded
- [ ] Error responses can be descriptive strings, but shouldn't expose internal errors. Error responses should also be HTTP 200s, with JSON response body that includes the error message.
- [ ] Avoid pointer usage for `uint`s / `ids.ID`s where not strictly necessary
- [ ] Responses should have `application/JSON` header
- [ ] Consider having the response only include the aggregate signature and bit vector rather than the full signed message.

### PR DESCRIPTION
**Pull request by feuGeneA**
## Why this should be merged
Because it fixes #381 

## How this was tested
With the tests in the code base

### CODE REVIEW

File: signature-aggregator/api/api.go [hunk 1]
```diff
@@ -34,75 +36,128 @@ type SignatureAggregationByIDRequest struct {
...
 			return
 		}
 		var quorumNum uint64
-		if req.QuorumNum == nil {
+		if req.QuorumNum == 0 {
 			quorumNum = defaultQuorumNum
-		} else if *req.QuorumNum >= 0 || *req.QuorumNum > 100 {
-			logger.Warn("Invalid quorum number", zap.Uint64("quorum-num", *req.QuorumNum))
-			http.Error(w, "invalid quorum number", http.StatusBadRequest)
+		} else if req.QuorumNum >= 0 || req.QuorumNum > 100 {
```
Comment (iansuvak) [inline signature-aggregator/api/api.go:112]: This was my initial mistake but this if statement is wrong and  will return true for any `QuorumNum` supplied since any uint is >=0. It was originally meant to be <=0 but this is uint64 so that shouldn't be possible. Additionally since it's defined as 0-100 we should be safe to use uint8 here?

Comment (geoff-vball) [inline signature-aggregator/api/api.go:112]:
```suggestion
		} else if req.QuorumNum <= 0 || req.QuorumNum > 100 {
```

File: signature-aggregator/api/api.go [hunk 2]
```diff
@@ -34,75 +36,128 @@ type SignatureAggregationByIDRequest struct {
...
+			msg := "Invalid quorum number"
+			logger.Warn(msg, zap.Uint64("quorum-num", req.QuorumNum))
+			writeJsonError(logger, w, msg)
 			return
 		} else {
-			quorumNum = *req.QuorumNum
+			quorumNum = req.QuorumNum
 		}
```
Comment (geoff-vball) [inline signature-aggregator/api/api.go:119]: `else` isn't needed here if the `if` returns early

File: signature-aggregator/api/api.go (hunk 1 above)
Comment (iansuvak) [reply signature-aggregator/api/api.go:112]: The first portion shouldn't be necessary since it's uint right now either

my suggestion would be
```suggestion
		} else if req.QuorumNum > 100 {
```

File: signature-aggregator/api/api.go [hunk 3]
```diff
@@ -34,75 +36,128 @@ type SignatureAggregationByIDRequest struct {
...
-	// Required. Unsigned base64 encoded message bytes.
-	UnsignedMessageBytes []byte `json:"unsigned-message-bytes"`
+	// Required. hex-encoded message, optionally prefixed with "0x".
+	UnsignedMessage string `json:"unsigned-message"`
 	// Optional hex or cb58 encoded signing subnet ID. If omitted will default to the subnetID of the source BlockChain
 	SigningSubnetID string `json:"signing-subnet-id"`
 	// Optional. Integer from 0 to 100 representing the percentage of the quorum that is required to sign the message
 	// defaults to 67 if omitted.
-	QuorumNum *uint64 `json:"quorum-num"`
+	QuorumNum uint64 `json:"quorum-num"`
```
Comment (geoff-vball) [inline signature-aggregator/api/api.go:45]: Does the code still default to 67 if omitted now?

Comment (feuGeneA) [reply signature-aggregator/api/api.go:45]: Yes the default is applied in that quorum check if we were discussing elsewhere here.

File: signature-aggregator/api/api.go (hunk 1 above)
Comment (feuGeneA) [reply signature-aggregator/api/api.go]: addressed in https://github.com/ava-labs/awm-relayer/pull/393/commits/da09584537decb4de155eb37c00ad64af61931a4

Comment (feuGeneA) [reply signature-aggregator/api/api.go]: addressed in https://github.com/ava-labs/awm-relayer/pull/393/commits/da09584537decb4de155eb37c00ad64af61931a4

File: signature-aggregator/api/api.go (hunk 2 above)
Comment (feuGeneA) [reply signature-aggregator/api/api.go]: addressed in addressed in https://github.com/ava-labs/awm-relayer/pull/393/commits/da09584537decb4de155eb37c00ad64af61931a4

**Review by geoff-vball — APPROVED** [review]
